name: Nur Muhammad Shafiullah
subname: Nur Muhammad Shafiullah - All of time and space, anywhere and everywhere, where do you want to start?
markdown: redcarpet
pygments: true
excerpt_separator: <!--more-->